### ISSUE TITLE
Issue 1 - Bug on ipv6 eggdrop.

### ISSUE THREAD

**Issue by fahadmehar** [sirfz/allprotection#2] opened 2016-09-06 03:35 UTC
When we RUN AllPro 4.7 on ipv6 eggdrops. It got disconnect. Then we have to "disable"
(Anti-Spam) in TCL because we got (Anti-Spam) error. Need to fix this issue on upcoming Ver of All Protection TCL. Should work on ipv6 eggdrops.

**Comment by sirfz** [comment] 2016-09-06 20:48
Just to make sure we're on the same page, by "ipv6 eggdrops" you mean Eggdrop 1.8?

**Comment by fahadmehar** [comment] 2016-09-07 03:07
Yes. New version of Eggdrop.

**Comment by sirfz** [comment] 2016-09-08 16:34
I've pushed a fix for this issue into the [eggdrop1.8-fixes branch](https://github.com/sirfz/allprotection.tcl/tree/eggdrop1.8-fixes). I tested it with Eggdrop 1.8 and can confirm the Antispam bot is now working on it.

Let me know if you still face any issues with Eggdrop 1.6 or 1.8.

**Comment by fahadmehar** [comment] 2016-09-09 03:54
Thanks so much. Really appriciati it... I am very serious about channel protection... I will let you know when I see any issue or bug and when this TCL will be release ?

**Comment by fahadmehar** [comment] 2016-09-09 05:09
[04:52:11] Tcl error in file 'eggdrop.conf':
[04:52:11] can't read "my-ip": no such variable
    while executing
"set antispam(ip) ${my-ip}"
    (in namespace eval "::AllProtection" script line 365)
    invoked from within
"namespace eval AllProtection {

# Basic declarations: (don't touch)
variable declr
foreach declr {textl textc notcl notcc capsp repeatf codesf adexemp..."
    (file "scripts/allprotection.tcl" line 159)
    invoked from within
"source scripts/allprotection.tcl"
    (file "eggdrop.conf" line 215)
[04:52:11] * CONFIG FILE NOT LOADED (NOT FOUND, OR ERROR)

**Comment by fahadmehar** [comment] 2016-09-09 05:22
I download TCL from this site and i load I get this error message

```
[04:52:11] Tcl error in file 'eggdrop.conf':
[04:52:11] can't read "my-ip": no such variable
    while executing
"set antispam(ip) ${my-ip}"
    (in namespace eval "::AllProtection" script line 365)
    invoked from within
"namespace eval AllProtection {

# Basic declarations: (don't touch)
variable declr
foreach declr {textl textc notcl notcc capsp repeatf codesf adexemp..."
    (file "scripts/allprotection.tcl" line 159)
    invoked from within
"source scripts/allprotection.tcl"
    (file "eggdrop.conf" line 215)
[04:52:11] * CONFIG FILE NOT LOADED (NOT FOUND, OR ERROR)
```

**Comment by sirfz** [comment] 2016-09-09 12:57
You didn't load the version from the branch I linked you, the correct file is https://github.com/sirfz/allprotection.tcl/blob/eggdrop1.8-fixes/allprotection.tcl

Test it out and let me know if the issue is solved.

**Comment by fahadmehar** [comment] 2016-09-10 07:06
TCL is Loaded. Thanks alot. I will check further.

**Closed as completed** 2016-09-15 15:36 UTC
Labels: bug
